### Simple GET request
GET http://localhost:3003/api/blogs

### Add a new person (valid schema) --> twice for Name must be unique
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "GregorFoitzik",
    "url": "http://localhost:3001/api/blogs/test_blog",
    "likes": 0
}